services:
  api:
    container_name: api
    build: ./backend
    restart: always
    ports:
      - 8080:8080
      
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - react-volume:/var/www/html
      - bkp:/var/www/html/bkp
  
  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - bkp:/var/www/html/bkp
      - ssl-certs:/certs
    depends_on:
      - api
      - frontend

volumes:
  react-volume:
  ssl-certs:
  bkp:
