services:
  api:
    container_name: flight-search-api
    build: ./backend
    restart: always
    ports:
      - 8080:8080
      
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - react-volume:/var/www/html
  
  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - api
      - frontend

volumes:
  react-volume:
  ssl-certs:
