services:
  api:
    container_name: api
    build: ./backend
    restart: always
    ports:
      - 8080:8080
      
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - react-volume:/var/www/html
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - api
      - frontend

volumes:
  react-volume:
